Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -37,10 +37,10 @@ jobs:
       run: chmod +x gradlew
 
     - name: Build with Gradle
-      run: ./gradlew build --info
+      run: ./gradlew build --info || { echo "Build failed"; exit 1; }
 
     - name: Run tests
-      run: ./gradlew test --info
+      run: ./gradlew test --info || { echo "Tests failed"; exit 1; }
 
     - name: Archive test results
       if: always()
